### ISSUE TITLE
兼容性测试Android 5.x：14/14的手机启动失败

### ISSUE THREAD

**Issue by Weiyi-C** [13568810905/WeiyiChild#2]
Android 5 全崩
```log
java.lang.NoSuchMethodError: No virtual method  
getColor(ILandroid/content/res/Resources$Theme;)I in class Landroid/content/res/Resources;  
or its super classes (declaration of 'android.content.res.Resources' appears in  
/system/framework/framework.jar)
  at cn.zhengweiyi.weiyichild.custom.StatusBarUtil.setStatusBarColor(StatusBarUtil.java:56)
  at cn.zhengweiyi.weiyichild.custom.StatusBarUtil.setStatusBarMode(StatusBarUtil.java:81)
  at cn.zhengweiyi.weiyichild.MainActivity.onCreate(MainActivity.java:68)
```

![兼容性测试报告](https://user-images.githubusercontent.com/34223095/54936271-1c7cbb00-4f5d-11e9-8f0b-af974c2e4991.png)

**Comment by Weiyi-C** [comment]
bug 已修复
